### ISSUE TITLE
Run Stanford CoreNLP lemmatizer for jpype backend

### ISSUE THREAD

**Issue by kaushikacharya** [ncbi-nlp/NegBio#13]
JPypeBackend.py of StanfordDependencies allows option to use Stanford CoreNLP lemmatizer using the input parameter: _add_lemmas_
https://github.com/dmcc/PyStanfordDependencies/blob/master/StanfordDependencies/JPypeBackend.py#L86

But NegBio isn't utilizing this option for backend=jpype

I have compared NLTK wordnet vs CoreNLP lemmatization in terms of speed on few sentences.
CoreNLP is much faster(almost 10 times).
For this had made the following changes:

1. passed add_lemmas=True
2. populated ann.infons['lemma'] from dependency graph (https://github.com/ncbi-nlp/NegBio/blob/master/negbio/pipeline/ptb2ud.py#L107)

How about making this change to utilize CoreNLP lemmatization?

**Comment by yfpeng** [comment]
I will add it in the next version.
