### ISSUE TITLE
negbio_pipeline parse fails silently

### ISSUE THREAD

**Issue by vadim0x60** [ncbi-nlp/NegBio#18]
Whenever my BioC XML file with documents contains any sentences that BLLIP parser fails to parse `negbio_pipeline parse` just terminates and does not produce any output files nor error messages. The only way I know of to find out which sentence causes issues is binary search: keep splitting XML and running `negbio_pipeline parse` on the separate until you isolate the problematic sentence.

It would be a lot more convenient to get an error message with details and/or just skip the problematic sentence and parse the rest of the dataset.

**Comment by yfpeng** [comment]
I think I have catched the exception and skipped the sentence (https://github.com/ncbi-nlp/NegBio/blob/master/negbio/pipeline/parse.py#L58)

**Comment by vadim0x60** [comment]
Yes, but sometimes when you try to parse an empty sentence, something breaks badly and `bllip` doesn't just raise an exception, but crashes entirely.

I had to introduce this hack to make it work:

    for passage in document.passages:
        for sentence in passage.sentences:     
            if sentence.text.isspace():
                 continue

            try:
                text = sentence.text
                tree = self.parse(text)
                sentence.infons['parse tree'] = str(tree)
            except:
                logging.exception('Cannot parse sentence: {}'.format(sentence.offset))

**Comment by yfpeng** [comment]
I think it is a good way to handle it. Bllip parser is not maintained by us.

**Comment by yfpeng** [comment]
Fixed in #20
