### ISSUE TITLE
Make GitHub releases that match with PyPi

### ISSUE THREAD

**Issue by alistairewj** [ncbi-nlp/NegBio#21]
Great to see this installable on PyPi. I just installed it but found there have been some updates to NegBio since and it wasn't really clear to me when it was put up on PyPi. It would be great to created releases on GitHub which are tagged with the same version as on PyPi (or maybe you can point me to where that's already done, if so).

**Comment by yfpeng** [comment]
Thanks for your advice. The current version is 0.9.4 now on both GitHub and PyPi.
