### ISSUE TITLE
A BioCAnnotation no longer has the attribute get_total_location() in the latest bioc version(1.3) 

### ISSUE THREAD

**Issue by aavshr** [ncbi-nlp/NegBio#32]
For instance, in ```NegBio/negbio/pipeline/negdetect.py```, in ``` detect(document, detector) ```

``` 
locs = []
for ann in passage.annotations:
     total_loc = ann.get_total_location()
 ```

```get_total_location()``` no longer exists and is instead replaced by ```total_span()```.

**Comment by yfpeng** [comment]
I don't suggest you use bioc==1.3, but use bioc==1.1.dev3. I haven't got a chance to test the new version of bioc in NegBio. I am afraid there will be more issues.

**Comment by kaushikacharya** [comment]
With  bioc version 1.1.dev3,
 `ann.get_total_location()` works fine.

You can also replace that with `ann.total_span`
Note that total_span is a property. You don't need to put the parentheses: `()`

@yfpeng 
It would be better, if in the pypi package for different versions of bioc, its mentioned which one is compatible with python 2 and which one is compatible with python 3.
What happens now is if one is using python 2, and he/she does pip install bioc, it downloads the latest release which is only compatible with python 3.

I understand that in https://github.com/ncbi-nlp/NegBio/blob/master/requirements.txt you have mentioned `bioc==1.1.dev3`
But perhaps if it can be done at pypi packaging, it would not lead to this kind of confusion.
There are other threads also where people have faced similar issue: https://github.com/yfpeng/bioc/issues/7

**Comment by yfpeng** [comment]
Since python 2 will not be maintained past 2020, I am considering not to support python 2 in future.
