### ISSUE TITLE
Version for Portuguese-BR

### ISSUE THREAD

**Issue by gazzola** [ncbi-nlp/NegBio#37]
Does anyone know any version adapted for Brazilian Portuguese?

**Comment by kaushikacharya** [comment]
@gazzola 
First step in NegBio pipeline is extraction of UMLS concepts from the given text. This is being done by MetaMap.

According to MetaMap paper: [An overview of MetaMap: historical perspective and recent advances](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2995713/)

> One of MetaMap's weaknesses is that it can be **applied only to English text**. MetaMap's English-centric nature is evident throughout its implementation, not just in its lexical and syntactic algorithms.

So if you want to build NegBio pipeline, first thing is you would  need to replace MetaMap by an alternate concept extraction library.
After that you would need parse tree and dependency tree creation specific to Portuguese-BR language.
And then in NegBio, negation/uncertain patterns also would be needed specific to Portuguese-BR language
