### ISSUE TITLE
AttributeError: Java package 'edu' is not valid

### ISSUE THREAD

**Issue by MaryFllh** [ncbi-nlp/NegBio#44]
I install NegBio by cloning the repo and try running ` main_chexpert text --output=examples examples/00000086.txt examples/00019248.txt` which downloads a .jar file from `http://search.maven.org/remotecontent?filepath=edu/stanford/nlp/stanford-corenlp/3.5.2/stanford-corenlp-3.5.2.jar` and puts it in  `/root/.local/share/pystanforddeps/`, however get an error from `StanfordDependencies/JPypeBackend.py`:
 `AttributeError: Java package 'edu' is not valid`
Please assist. Thanks.

**Comment by tealeeseng** [comment]
Works for me after "pip uninstall jpype1"
negbio uses subprocess backend if jpype failed to import.
refer "$VENV/lib/python3.6/site-packages/negbio/pipeline/ptb2ud.py", line 70, in __init__
