### ISSUE TITLE
Highlighting need for giving META_MAP_HOME as absolute path

### ISSUE THREAD

**Issue by kaushikacharya** [ncbi-nlp/NegBio#7]
Though this is not a bug as such but would suggest to highlight the importance of mentioning META_MAP_HOME as **absolute path** in [getting started page](http://negbio.readthedocs.io/en/latest/getting_started.html).

NegBio uses pymetamap where there's a [discussion thread](https://github.com/AnthonyMRios/pymetamap/issues/9) on issue related to giving path as something like ~/username/path. I myself had spent quite sometime with this issue. So its better if this is highlighted so that future users don't have to struggle with this issue.

**Comment by yfpeng** [comment]
Changed. Thank you!
